"""add parent tags remark

Revision ID: 9204a7ab6aa2
Revises: ca7cd93fdc36
Create Date: 2026-08-26 22:09:28.236200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9204a7ab6aa2'
down_revision: Union[str, None] = 'ca7cd93fdc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # parent_users 已有存量行，SQLite 不允许直接加 NOT NULL 无默认值列，
    # 故加 server_default='' 让存量行有默认值，再保持 NOT NULL 约束。
    op.add_column('parent_users', sa.Column('tags', sa.String(length=255), nullable=False, server_default='', comment='患者标签（逗号分隔）'))
    op.add_column('parent_users', sa.Column('remark', sa.Text(), nullable=False, server_default='', comment='患者备注（仅后台可见）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_users', 'remark')
    op.drop_column('parent_users', 'tags')
    # ### end Alembic commands ###
