"""init_27_tables

Revision ID: ca7cd93fdc36
Revises: 
Create Date: 2026-08-26 19:55:49.737324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7cd93fdc36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='操作人(管理员 id)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作，如 create/update/delete/confirm'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='对象类型，如 service/appointment'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='对象 id'),
    sa.Column('detail', sa.Text(), nullable=False, comment='操作详情(JSON/文本)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_categories',
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序，小在前'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('path', sa.String(length=255), nullable=False, comment='逻辑路径 uploads/2026/08/x.jpg（无 /media）'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='素材分类'),
    sa.Column('mime', sa.String(length=50), nullable=False, comment='MIME 类型'),
    sa.Column('size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('width', sa.Integer(), nullable=False, comment='图片宽'),
    sa.Column('height', sa.Integer(), nullable=False, comment='图片高'),
    sa.Column('ref_count', sa.Integer(), nullable=False, comment='引用计数，>0 禁止删除'),
    sa.Column('deleted_at', sa.String(length=20), nullable=True, comment='删除时间；5 秒恢复窗口'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('benefits',
    sa.Column('name', sa.String(length=100), nullable=False, comment='权益名称'),
    sa.Column('desc', sa.Text(), nullable=False, comment='权益说明'),
    sa.Column('valid_days', sa.Integer(), nullable=False, comment='有效天数（0=长期）'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guestbooks',
    sa.Column('name', sa.String(length=50), nullable=False, comment='留言人姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='联系手机号'),
    sa.Column('content', sa.Text(), nullable=False, comment='留言内容'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0=未处理 1=已处理'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_items',
    sa.Column('item_type', sa.String(length=30), nullable=False, comment='区块类型'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=200), nullable=False, comment='副标题'),
    sa.Column('image', sa.String(length=255), nullable=False, comment='图片（逻辑路径）'),
    sa.Column('link', sa.String(length=255), nullable=False, comment='跳转链接'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序；拖拽排序见 /admin/home-items/{id}/sort'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=上架 0=下架'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='父菜单 id，0=一级'),
    sa.Column('path', sa.String(length=100), nullable=False, comment='前端路由 path'),
    sa.Column('icon', sa.String(length=50), nullable=False, comment='图标名'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=显示 0=隐藏'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_units',
    sa.Column('name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='父级 id，0=根'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型 company/region/store'),
    sa.Column('store_id', sa.Integer(), nullable=True, comment='关联门店（type=store 时）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('slug', sa.String(length=30), nullable=False, comment='页面标识 privacy/terms/disclaimer'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='页面标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文（富文本 HTML）'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=已发布 0=草稿'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('parent_users',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号（登录账号）'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=False, comment='头像（逻辑路径）'),
    sa.Column('password_hash', sa.String(length=100), nullable=False, comment='bcrypt 密码哈希（见 §9 安全）'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=正常 0=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=50), nullable=False, comment='权限点编码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='权限点名称'),
    sa.Column('group', sa.String(length=30), nullable=False, comment='分组，如 cms/store/appointment/system'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='角色编码'),
    sa.Column('data_scope', sa.String(length=10), nullable=False, comment='数据范围 all/store'),
    sa.Column('remark', sa.Text(), nullable=False, comment='角色说明'),
    sa.Column('is_builtin', sa.Integer(), nullable=False, comment='是否内置 1/0（内置不可删）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序，小在前'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_config',
    sa.Column('site_name', sa.String(length=100), nullable=False, comment='站点名称（如 悦芽口腔）'),
    sa.Column('icp_number', sa.String(length=50), nullable=False, comment='ICP 备案号'),
    sa.Column('contact_phone', sa.String(length=30), nullable=False, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=80), nullable=False, comment='联系邮箱'),
    sa.Column('contact_address', sa.String(length=255), nullable=False, comment='联系地址'),
    sa.Column('multi_store_on', sa.Integer(), nullable=False, comment='是否开启多门店 1/0'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('name', sa.String(length=100), nullable=False, comment='门店名称'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='详细地址'),
    sa.Column('lng', sa.Float(), nullable=True, comment='经度'),
    sa.Column('lat', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('phone', sa.String(length=30), nullable=False, comment='门店电话'),
    sa.Column('hours', sa.String(length=100), nullable=False, comment='营业时间描述'),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='门店封面（逻辑路径，无 /media）'),
    sa.Column('intro', sa.Text(), nullable=False, comment='门店简介'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=营业中 0=筹建中'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verify_codes',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('code_hash', sa.String(length=100), nullable=False, comment='验证码哈希(不存明文)'),
    sa.Column('expires_at', sa.String(length=20), nullable=False, comment='过期时间(UTC，5 分钟)'),
    sa.Column('used', sa.Integer(), nullable=False, comment='0=未用 1=已用(防重放)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号(非中文)'),
    sa.Column('password_hash', sa.String(length=100), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='显示名'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('org_id', sa.Integer(), nullable=True, comment='所属组织'),
    sa.Column('store_id', sa.Integer(), nullable=True, comment='负责门店（顾问本门店隔离）'),
    sa.Column('last_login_at', sa.String(length=20), nullable=True, comment='最后登录时间(UTC)，未登录为 NULL'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=正常 0=停用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='所属文章分类'),
    sa.Column('author', sa.String(length=50), nullable=False, comment='作者'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('summary', sa.Text(), nullable=False, comment='摘要'),
    sa.Column('body', sa.Text(), nullable=False, comment='正文（富文本 HTML）'),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='封面（逻辑路径）'),
    sa.Column('seo_title', sa.String(length=200), nullable=False, comment='SEO 标题'),
    sa.Column('seo_keywords', sa.String(length=200), nullable=False, comment='SEO 关键词'),
    sa.Column('seo_description', sa.String(length=255), nullable=False, comment='SEO 描述'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量（详情接口 +1）'),
    sa.Column('published_at', sa.String(length=20), nullable=False, comment='发布时间(UTC，响应转上海时区)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=已发布 0=草稿'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='所属家长'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='孩子姓名'),
    sa.Column('gender', sa.Integer(), nullable=False, comment='1=男 2=女'),
    sa.Column('birth_date', sa.String(length=10), nullable=False, comment='出生日期 YYYY-MM-DD'),
    sa.Column('remark', sa.Text(), nullable=False, comment='备注（过敏史等，仅后台可见）'),
    sa.Column('first_visit', sa.Integer(), nullable=False, comment='1=首诊 0=否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('store_id', sa.Integer(), nullable=False, comment='所属门店'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='医生姓名'),
    sa.Column('title', sa.String(length=50), nullable=False, comment="职称，如 '主治医师'"),
    sa.Column('good_at', sa.Text(), nullable=False, comment='擅长领域'),
    sa.Column('intro', sa.Text(), nullable=False, comment='个人简介'),
    sa.Column('avatar', sa.String(length=255), nullable=False, comment='头像（逻辑路径）'),
    sa.Column('schedule_desc', sa.String(length=255), nullable=False, comment='出诊/排班说明'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=在岗 0=休假'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限点'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='所属项目分类'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('price_range', sa.String(length=50), nullable=False, comment="价格区间描述，如 '￥800-1500'"),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='项目封面（逻辑路径）'),
    sa.Column('age_range', sa.String(length=50), nullable=False, comment="适用年龄描述，如 '3-12岁'"),
    sa.Column('intro', sa.Text(), nullable=False, comment='项目介绍'),
    sa.Column('flow', sa.Text(), nullable=False, comment='就诊流程(JSON)'),
    sa.Column('faq', sa.Text(), nullable=False, comment='常见问题(JSON)'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=上架 0=下架'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('appointment_no', sa.String(length=30), nullable=False, comment='预约单号 AP+YYYYMMDD+序号'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='家长（匿名提交时可为空）'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='门店'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='诊疗项目'),
    sa.Column('child_id', sa.Integer(), nullable=True, comment='孩子（匿名时可为空）'),
    sa.Column('want_date', sa.String(length=10), nullable=False, comment='意向日期 YYYY-MM-DD'),
    sa.Column('want_slot', sa.String(length=20), nullable=False, comment='意向时段'),
    sa.Column('confirmed_store_id', sa.Integer(), nullable=True, comment='确认门店'),
    sa.Column('confirmed_doctor_id', sa.Integer(), nullable=True, comment='确认医生'),
    sa.Column('confirmed_date', sa.String(length=10), nullable=True, comment='确认日期'),
    sa.Column('confirmed_slot', sa.String(length=20), nullable=True, comment='确认时段'),
    sa.Column('advisor_id', sa.Integer(), nullable=True, comment='跟进顾问(管理员 id)'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人姓名（匿名也填）'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系手机号'),
    sa.Column('note', sa.Text(), nullable=False, comment='备注/诉求'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='获客渠道 web/...（看板用）'),
    sa.Column('cancel_reason', sa.Text(), nullable=True, comment='取消原因（仅取消时填写，其余状态为空）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/confirmed/completed/cancelled'),
    sa.Column('is_deleted', sa.Integer(), nullable=False, comment='软删 1/0；列表过滤'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_no')
    )
    op.create_table('cases',
    sa.Column('service_id', sa.Integer(), nullable=False, comment='关联诊疗项目'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='案例标题'),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='案例封面（逻辑路径）'),
    sa.Column('gallery', sa.Text(), nullable=False, comment='图集(JSON，逻辑路径)'),
    sa.Column('age_bucket', sa.String(length=20), nullable=False, comment='年龄分桶 3-6/6-9/9-12'),
    sa.Column('anonymous_desc', sa.Text(), nullable=False, comment='匿名化说明（合规：不暴露可识别信息，见 §15）'),
    sa.Column('summary', sa.Text(), nullable=False, comment='案例摘要'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=已发布 0=草稿'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='医生'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='门店'),
    sa.Column('work_date', sa.String(length=10), nullable=False, comment='出诊日期 YYYY-MM-DD'),
    sa.Column('slot', sa.String(length=20), nullable=False, comment='时段，如 09:00-10:00'),
    sa.Column('available', sa.Integer(), nullable=False, comment='1=可约 0=不可约'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'store_id', 'work_date', 'slot', name='uq_schedule_doctor_date_slot')
    )
    op.create_table('appointment_followups',
    sa.Column('appointment_id', sa.Integer(), nullable=False, comment='关联预约单（级联删）'),
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='跟进人(管理员 id)'),
    sa.Column('content', sa.Text(), nullable=False, comment='跟进内容'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键自增'),
    sa.Column('is_activate', sa.Integer(), nullable=False, comment='行级启停：1=启用 0=禁用（可见性判据）'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建人（存登录账号 username，非时间！）'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='创建时间(UTC)，应用层写入'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='修改人（存登录账号 username）'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='修改时间(UTC)，应用层写入'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_followups')
    op.drop_table('schedules')
    op.drop_table('cases')
    op.drop_table('appointments')
    op.drop_table('services')
    op.drop_table('role_permissions')
    op.drop_table('role_menus')
    op.drop_table('doctors')
    op.drop_table('children')
    op.drop_table('articles')
    op.drop_table('admins')
    op.drop_table('verify_codes')
    op.drop_table('stores')
    op.drop_table('site_config')
    op.drop_table('service_categories')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('parent_users')
    op.drop_table('pages')
    op.drop_table('org_units')
    op.drop_table('menus')
    op.drop_table('home_items')
    op.drop_table('guestbooks')
    op.drop_table('benefits')
    op.drop_table('assets')
    op.drop_table('article_categories')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
